variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: "The version of the packages to build"
    # x-release-please-start-version
    default: "0.1.1"
    # x-release-please-end